export const jobPresets = {
  'software_engineer': {
    job_description: "Looking for a software engineer with strong programming skills in Python and JavaScript. Must have experience with web development frameworks and cloud technologies.",
    job_title: "Software Engineer",
    query: "software engineer",
    soft_skills: ["communication", "teamwork", "problem solving"],
    hard_skills: ["python", "javascript", "aws", "docker"],
    location_flexibility: "remote",
    contract_type: "full_time",
    education_level: "bachelors",
    seniority: "mid",
    min_years_experience: 3,
    field_of_study: ["computer science", "software engineering"],
  },
  'data_scientist': {
    job_description: "Seeking a data scientist with expertise in machine learning and statistical analysis. Experience with Python, R, and big data technologies required.",
    job_title: "Data Scientist",
    query: "data scientist",
    soft_skills: ["analytical thinking", "research", "communication"],
    hard_skills: ["python", "machine learning", "sql", "tensorflow"],
    location_flexibility: "hybrid",
    contract_type: "full_time",
    education_level: "masters",
    seniority: "senior",
    min_years_experience: 5,
    field_of_study: ["data science", "statistics", "mathematics"],
  },
  'product_manager': {
    job_description: "Looking for an experienced product manager to lead product development initiatives. Strong background in agile methodologies and product lifecycle management required.",
    job_title: "Product Manager",
    query: "product manager",
    soft_skills: ["leadership", "strategic thinking", "stakeholder management"],
    hard_skills: ["agile", "jira", "product development", "market research"],
    location_flexibility: "onsite",
    contract_type: "full_time",
    education_level: "bachelors",
    seniority: "senior",
    min_years_experience: 7,
    field_of_study: ["business administration", "computer science"],
  },
};
